import 'package:flutter/material.dart';
import '../../state/app_state.dart';
import '../../models/lecture_model.dart';
import 'package:file_picker/file_picker.dart';

class CreateScreen extends StatefulWidget {
  const CreateScreen({super.key});

  @override
  State<CreateScreen> createState() => _CreateScreenState();
}

class _CreateScreenState extends State<CreateScreen> {
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _contentController = TextEditingController();
  bool _isLoading = false;
  String? _attachedFileName;
  PlatformFile? _attachedFile;

  void _createLecture() async {
    final title = _nameController.text.trim();
    if (title.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a lecture name')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    // Make the API request to the backend
    bool success = await appState.addLecture(LectureModel(
      id: '', // Generated by backend
      title: title,
      content: _contentController.text,
      dateText: "Created Just Now",
      questions: 0,
      colorIcon: "blue",
      documents: _attachedFileName != null ? [_attachedFileName!] : [],
    ));

    if (mounted) {
      setState(() {
        _isLoading = false;
        if (success) {
          _nameController.clear();
          _contentController.clear();
          _attachedFileName = null;
        }
      });

      if (success) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Lecture created successfully! Check the Library.')),
        );
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(appState.errorMessage.isNotEmpty ? appState.errorMessage : 'Failed to create lecture.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("New Lecture", style: TextStyle(fontWeight: FontWeight.bold)),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text("Add Content", style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              const Text("Paste your notes or upload a document to let our AI generate study questions, flashcards, and quizzes for you.", style: TextStyle(color: Colors.grey, height: 1.5)),
              const SizedBox(height: 30),
              
              const Text("LECTURE NAME", style: TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1.2)),
              const SizedBox(height: 10),
              Container(
                decoration: BoxDecoration(
                  color: const Color(0xff222536),
                  borderRadius: BorderRadius.circular(15),
                ),
                child: TextField(
                  controller: _nameController,
                  decoration: const InputDecoration(
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.symmetric(horizontal: 15, vertical: 15),
                    hintText: "Enter the name of your lecture...",
                    hintStyle: TextStyle(color: Colors.grey),
                  ),
                  style: const TextStyle(color: Colors.white),
                ),
              ),
              const SizedBox(height: 30),

              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text("LECTURE CONTENT", style: TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1.2)),
                  TextButton.icon(
                    onPressed: () {},
                    icon: const Icon(Icons.paste, size: 16, color: Colors.blueAccent),
                    label: const Text("Paste", style: TextStyle(color: Colors.blueAccent)),
                    style: TextButton.styleFrom(
                      padding: EdgeInsets.zero,
                      minimumSize: const Size(50, 20),
                      tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                    ),
                  )
                ],
              ),
              const SizedBox(height: 10),
              Container(
                height: 200,
                padding: const EdgeInsets.all(15.0),
                decoration: BoxDecoration(
                  color: const Color(0xff222536),
                  borderRadius: BorderRadius.circular(15),
                ),
                child: TextField(
                  controller: _contentController,
                  maxLines: null,
                  decoration: const InputDecoration(
                    border: InputBorder.none,
                    hintText: "Start typing or paste your lecture notes here...",
                    hintStyle: TextStyle(color: Colors.grey),
                  ),
                  style: const TextStyle(color: Colors.white),
                ),
              ),
              const SizedBox(height: 8),
              const Align(
                alignment: Alignment.centerRight,
                child: Text("0 / 5000 chars", style: TextStyle(color: Colors.grey, fontSize: 10)),
              ),
              
              const SizedBox(height: 20),
              const Center(child: Text("OR", style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold))),
              const SizedBox(height: 20),
              
              const Text("UPLOAD DOCUMENT", style: TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1.2)),
              const SizedBox(height: 10),
              InkWell(
                onTap: () async {
                  try {
                    final result = await FilePicker.platform.pickFiles(
                      type: FileType.custom,
                      allowedExtensions: ['pdf', 'txt', 'doc', 'docx'],
                      withData: true,
                    );
                    if (result != null && result.files.isNotEmpty) {
                      _attachedFile = result.files.first;
                      setState(() {
                        _attachedFileName = _attachedFile!.name;
                        if (_nameController.text.isEmpty) {
                          _nameController.text = _attachedFile!.name;
                        }
                        _contentController.text = "Attached Document: ${_attachedFile!.name}\n\n(AI will extract content from this document automatically on the backend.)";
                      });
                      if (mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Attached ${_attachedFile!.name}')));
                      }
                    }
                  } catch (e) {
                    if (mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error picking file: $e')));
                    }
                  }
                },
                borderRadius: BorderRadius.circular(15),
                child: Container(
                  height: 120,
                  decoration: BoxDecoration(
                    color: const Color(0xff222536),
                    borderRadius: BorderRadius.circular(15),
                  ),
                  child: const Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.upload_file, color: Colors.blueAccent, size: 40),
                        SizedBox(height: 10),
                        Text("Tap to upload PDF or Text", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.white)),
                        SizedBox(height: 4),
                        Text("Max file size 10MB", style: TextStyle(color: Colors.grey, fontSize: 12)),
                      ],
                    )
                  ),
                ),
              ),
              
              const SizedBox(height: 40),
              
              SizedBox(
                width: double.infinity,
                height: 55,
                child: ElevatedButton.icon(
                  onPressed: _isLoading ? null : _createLecture,
                  icon: _isLoading 
                      ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                      : const Icon(Icons.auto_awesome, color: Colors.white),
                  label: Text(_isLoading ? "Saving..." : "AI Generate Study Set", style: const TextStyle(fontSize: 18, color: Colors.white, fontWeight: FontWeight.bold)),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blueAccent,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 15),
              const Center(child: Text("AI will extract key concepts and create interactive questions.", style: TextStyle(color: Colors.grey, fontSize: 12), textAlign: TextAlign.center)),
            ],
          ),
        ),
      ),
    );
  }
}
